version: '3.1'
services:
    proxy:
        image: nginx
        container_name: proxy
        restart: unless-stopped
        ports: 
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
    md:
        build: .
        container_name: md
        restart: unless-stopped
        ports: 
            - 3000:3000
        volumes: 
            - ./site/docs:/site/docs
            - ./site/README.md:/site/README.md
